name: docker_register_cloud
description: The network disk client based on the Docker warehouse protocol can use many free container warehouse services for network disk storage, download and sharing.
version: 1.6.1

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  args: ^2.0.0
  http: ^0.12.1
  chewie: ^0.12.2
  crypto: ^2.1.3
  filesize: ^1.0.4
  provider: ^4.1.0
  open_file: ^3.0.1
  file_picker: ^2.1.5
  url_launcher: ^5.4.5
  angel_static: ^2.1.3
  synchronized: ^2.2.0
  video_player_web: '^0.1.4'
  path_provider: ^1.6.8
  angel_framework: ^2.0.0
  json_annotation: ^4.0.0
  shared_preferences: ^0.5.7
  permission_handler: ^5.0.0
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^4.0.0
flutter:
  uses-material-design: true